### ISSUE TITLE
npm error.

### ISSUE THREAD

**Issue by liuhao2050** [macacajs/macaca-test-sample-python#1]
Hello, I want to try this awesome test but when I run
`sudo npm install -g macaca-cli macaca-electron`
I got an error like this.

```
> electron-prebuilt@0.37.8 postinstall /usr/local/lib/node_modules/macaca-electron/node_modules/electron-prebuilt
> node install.js
npm ERR! not ok code 0

```
OS: Ubuntu 14.04 LTS

Could somebody help me？

**Comment by zenzhu** [comment]
Cross the great wall.

**Comment by liuhao2050** [comment]
Oh, well～

**Comment by zenzhu** [comment]
or
export CHROMEDRIVER_CDNURL=http://npm.taobao.org/mirrors/chromedriver/
export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
