### ISSUE TITLE
error when i run python test

### ISSUE THREAD

**Issue by lianghuiling** [macacajs/macaca-test-sample-python#2]
when i run python sample test(https://github.com/macacajs/macaca-test-sample-python), errors occued like this:
![image](https://cloud.githubusercontent.com/assets/16145060/17829005/4d5b23ae-66d2-11e6-9dad-aa4adcc272fb.png)

macaca server has started
![image](https://cloud.githubusercontent.com/assets/16145060/17829010/5f3881de-66d2-11e6-8122-5ee92abf715c.png)

anybody help?

**Comment by zenzhu** [comment]
Please try python3.4, python2.7 doesn't support keyword-only params.
