### ISSUE TITLE
iOS连接真机有问题

### ISSUE THREAD

**Issue by tongshan1** [macacajs/macaca-test-sample-python#4]
iOS:10.01
XCode:8.1
# macaca doctor:
 macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.8.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/library/java/javavirtualmachines/jdk1.8.0_91.jdk/contents/home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  platforms directory is not exist

  Installed driver list:

  ios: 1.0.46

# 运行日志：
ununtrium:auto-test-macaca sara$ macaca server --verbose
>> index.js:17:12 [master] pid:26691 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.1.36',
  host: 'ununtrium.local',
  loaded_time: '2016-11-30 15:00:36' }
>> middlewares.js:17:10 [master] pid:26691 base middlewares attached
>> router.js:129:10 [master] pid:26691 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:26691 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"udid":"xx","bundleId":"xx","platformName":"iOS","deviceName":"iPhone 5","platformVersion":"10.0"}}
>> session.js:47:10 [master] pid:26691 Creating session, sessionId: a87f462e-00df-475b-948a-3cf2b6de4860.
>> xctest-client.js:56:14 [master] pid:26691 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:144:10 [master] pid:26691 {
        "bundleId": "xx",
        "platformName": "iOS",
        "platformVersion": "10.0"
}
>> xctest-client start with port: 8901
>> xctest-client.js:233:14 [master] pid:26691 xcode version: 8.1
>> WebDriverAgent version: 1.0.36
>> xctest-client.js:170:14 [master] pid:26691 2016-11-30 15:00:54.695 xcodebuild[26699:638052]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/sara/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/14C4DEA6-7A8F-40EC-AC4A-4DF375D02C86/Session-WebDriverAgentRunner-2016-11-30_150054-WvzyJc.log

>> xctest-client.js:171:14 [master] pid:26691 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:26691 2016-11-30 15:00:54.695 xcodebuild[26699:638040] [MT] IDETestOperationsObserverDebug: (6280BC0C-AAD0-449A-831B-245DB3CBBE0D) Beginning test session WebDriverAgentRunner-6280BC0C-AAD0-449A-831B-245DB3CBBE0D at 2016-11-30 15:00:54.694 with Xcode 8B62 on target <DVTiOSDevice: 0x7f8805c41970> {
                deviceSerialNumber:         C39MDH81FRC5
                identifier:                 xx
                deviceClass:                iPhone
                deviceName:                 xx
                deviceIdentifier:           xx
                productVersion:             10.0.1
                buildVersion:               14A403
                deviceSoftwareVersion:      10.0.1 (14A403)
                deviceArchitecture:         arm64
                deviceTotalCapacity:        12088623104
                deviceAvailableCapacity:    7092183040
                deviceIsTransient:          NO
                ignored:                    NO
                deviceIsBusy:               NO
                deviceIsActivated:          YES
                deviceActivationState:      Activated
                deviceType:                 <DVTDeviceType:0x7f88036c97d0 Xcode.DeviceType.iPhone>
                supportedDeviceFamilies:    (
    1
)
                applications:              (null)
                provisioningProfiles:      (null)
                activityProgress:          -2
                activityTitle:             
                hasInternalSupport:        NO
                isSupportedOS:             YES
                developerDiskMountError:   (null)
(null)
        } (10.0.1 (14A403))

>> xctest-client.js:171:14 [master] pid:26691 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:26691 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/0q/d31vt2395c3gd028gzysbx3r0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/3c13836573226534d387cb31a1801fd8/43d388600e6a6f0ca35ed991f73ae96eb30f59aa/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/sara/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/0q/d31vt2395c3gd028gzysbx3r0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.cXZilO/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
        dst_ipa: /var/folders/0q/d31vt2395c3gd028gzysbx3r0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.cXZilO/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:171:14 [master] pid:26691 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:26691 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/0q/d31vt2395c3gd028gzysbx3r0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.cXZilO/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/0q/d31vt2395c3gd028gzysbx3r0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.cXZilO/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:171:14 [master] pid:26691 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:56:14 [master] pid:26691 Proxy: /session:POST to http://127.0.0.1:8901/session:POST with body: {"desiredCapabilities":{"bundleId":"xx","platformName":"iOS","platformVersion":"10.0"}}
>> proxy.js:79:20 [master] pid:26691 Got response with status 200: {"value":{"sessionId":"89DDFFA8-9DA0-4A2D-8EE4-E6CC5D03B0BE","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"10.0.1","CFBundleIdentifier":"local.pid.52"}},"sessionId":null,"status...
>> responseHandler.js:47:14 [master] pid:26691 Send HTTP Respone to Client: {"sessionId":"a87f462e-00df-475b-948a-3cf2b6de4860","status":0,"value":"{\"udid\":\"xx\",\"bundleId\":\"xx\",\"platformName\":\"iOS\",\"deviceName\":\"iPhone 5\",\"platformVersion\":\"10.0\"}"}

# python 报错日志
rror
Traceback (most recent call last):
  File "/Users/sara/PycharmProjects/auto-test-macaca/test.py", line 26, in setUpClass
    cls.driver.init()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/macaca/webdriver.py", line 132, in init
    }, False)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/macaca/webdriver.py", line 66, in _execute
    res = self.remote_invoker.execute(command, data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/macaca/remote_invoker.py", line 110, in execute
    return self._request(method, url, body)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/macaca/remote_invoker.py", line 145, in _request
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:3456/wd/hub/session
# python code:
```python
import unittest
import os
import time
from macaca import WebDriver


desired_caps = {
    'platformName': 'iOS',
    'platformVersion': '10.0',
    'deviceName': 'iPhone 5',
    'bundleId': 'xx',
    'udid': 'xx',
}

server_url = {
    'hostname': 'localhost',
    'port': 3456,
}

class MacacaTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = WebDriver(desired_caps, server_url)
        cls.driver.init()

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def test_01_login(self):
        self.driver.element('name', 'Clear').click()
        self.driver.element('name', '1').click()

if __name__ == '__main__':
    print(11)
    unittest.main()
```
ps：app-inspactor 可以打开，但是运行连接真机连不上。日志一直提示我： xctest-client.js:171:14 [master] pid:26691 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj 但是没有 说明错在哪。还有就是请问一下：app-inspactor 和macaca-ios 这两个里面的webDriverAgent是否安装一个到机器里？如果不是，2个区别是什么？

**Comment by tongshan1** [comment]
希望尽快能得到解答，感谢。

**Comment by zenzhu** [comment]
app-inspactor 和 macaca-ios 用的 WebDriverAgent 不是一个，导致个问题，就是要用另外一个的话，得先把机器上的 WebDriverAgent 删了重新安装和执行。

**Comment by tongshan1** [comment]
运行真机的话是需要安装macaca-ios 里的WebDriverAgent，是吧。我将机子里面的WebDriverAgent删了，重新安装后，运行。还是是提示我
please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj ，仍旧没有提示任何错误，最后就:
Testing failed:
        Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
请问是我WebDriverAgent配置有问题么？除了bundel ID的设置，还需要设置什么？

**Comment by tongshan1** [comment]
解决了，是app要用debug版的，但是please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj 这个提示信息仍然存在，还是同样的没有任何错误提示。
